//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Can_We_Fly.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Can_We_Fly.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;uk_airports&gt;
        ///	&lt;airport_info&gt;
        ///		&lt;icao_code&gt;X3AB&lt;/icao_code&gt;
        ///		&lt;airport_name&gt;Abbots Bromley&lt;/airport_name&gt;
        ///		&lt;alternate_name&gt;&lt;/alternate_name&gt;
        ///		&lt;latitude&gt;52°49&apos;39&quot;N&lt;/latitude&gt;
        ///		&lt;longitude&gt;1°53&apos;32&quot;W&lt;/longitude&gt;
        ///	&lt;/airport_info&gt;
        ///	&lt;airport_info&gt;
        ///		&lt;icao_code&gt;EGPD&lt;/icao_code&gt;
        ///		&lt;airport_name&gt;Aberdeen&lt;/airport_name&gt;
        ///		&lt;alternate_name&gt;Dyce&lt;/alternate_name&gt;
        ///		&lt;latitude&gt;57°12&apos;7&quot;N&lt;/latitude&gt;
        ///		&lt;longitude&gt;2°11&apos;52&quot;W&lt;/longitude&gt;
        ///	&lt;/airport_info&gt;
        ///	&lt;airport_info&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string airport_data {
            get {
                return ResourceManager.GetString("airport_data", resourceCulture);
            }
        }
    }
}
